name: process_train_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.22.2
  - pandas=1.4.1
  - eccodes=2.24.2
  - cfgrib=0.9.10.0
  - pip=20.3.3
  - pip:
      - ecmwflibs
      - xarray[complete]
